### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/stickers#1]
This issue is to collect ideas what to put on the sticker. @lgatto @sgibb , happy to get ideas.

**Comment by jorainer** [comment]
Having the R logo might not be bad to have - question is under what licence that is. And then we need something typical for MS data - a spectrum???

**Comment by jorainer** [comment]
suggestion for the logo:

<img width="710" alt="R4MS" src="https://user-images.githubusercontent.com/5506112/58878781-5e9c4880-86d4-11e9-845b-d02ffdc65830.png">

I don't know if it's obvious, but the idea is that you have different ions that get out of the *R*, accelerated and have different trajectories based on their *m/z*. Woudl be nice if the individual beams would have different colors.

**Comment by lgatto** [comment]
I really like it! 

And yes, the tof analyser was immediately obvious to me. It's a nice alternative of spectra or chromatograms.

**Comment by jorainer** [comment]
OK, so I'll work on a more advanced version - not hand-drawn this time...

**Comment by sgibb** [comment]
:+1: awesome!

**Comment by jorainer** [comment]
What do you say of that one? Suggestions/change requests welcome!

![R4MS-logo](https://user-images.githubusercontent.com/5506112/58936243-96a49980-876f-11e9-866c-7c0bf8223339.png)

**Comment by lgatto** [comment]
Nice! A couple of comments:
- With the current aspect ratio, will it fit nicely on a hex sticker? 
- The ions look a bit like fireworks, which distracts from the analyser idea
- What about trying to spell out Mass Spec(trometry) instead of MS - as discussed yesterday, MS is confusing unless one already knows the topic is mass spectrometry. That of course has major implications on the design...

**Comment by jorainer** [comment]
> - With the current aspect ratio, will it fit nicely on a hex sticker?

ah, well - kinda. There will be some white space above and below, but it should fit.

> - The ions look a bit like fireworks, which distracts from the analyser idea

right. I can make them smaller and less fuzzy - maybe that helps.

> - What about trying to spell out Mass Spec(trometry) instead of MS

Uh, well, then it becomes quite long (talking about hex sticker :) ). I think for the logo it should be OK to use MS instead of Mass Spec - logos should be clear and simple without much text. I can make one with Mass Spec, but am not convinced.

**Comment by jorainer** [comment]
Update: now with Mass Spec instead of MS and with smaller ions.

![R4MassSpec-logo](https://user-images.githubusercontent.com/5506112/58945939-1d17a600-8785-11e9-8247-6289504d4092.png)

**Comment by lgatto** [comment]
I find the ions are much better.
I don't know about MS vs Mass Spec in terms of niceness, but the latter isn't ambiguous.

**Comment by jorainer** [comment]
Agree - and now I even like the Mass Spec version :)

I will add a logo folder and put both of them.

**Comment by lgatto** [comment]
Would this text orientation be an option?

![IMG_20190605_125023~2](https://user-images.githubusercontent.com/384198/58951267-f1022200-8790-11e9-83fe-021645dd78e3.jpg)

**Comment by jorainer** [comment]
Could try that too - nice idea. In fact I reduced the font size of the MS slightly, so that it would look a little more *organized*.

![R4MassSpec-logo](https://user-images.githubusercontent.com/5506112/58952177-493a2380-8793-11e9-9e76-dfd4bcbbf9b9.png)

**Comment by jorainer** [comment]
I'm not convinced of the vertical arrangement of the characters. IMHO it get's too busy and you could start reading *ass pec* instead of *Mass Spec. So, I'd go for the version above.

![R4MassSpec-logo-vertical](https://user-images.githubusercontent.com/5506112/58958253-ccaf4100-87a2-11e9-8bba-d3bef51da843.png)

**Comment by lgatto** [comment]
Indeed. There would need to be a clear space between *ass* and *pec*, but even then, I'm not sure it's a good idea to have ass spelled out on a logo :-)

**Comment by jorainer** [comment]
OK in case @sgibb has no objections on the logo I would also play around with a sticker :) or a t-shirt ;)

**Comment by sgibb** [comment]
I like the latest version with the horizontal Mass/Spec and the slightly smaller font. 
While I very happy with that just a few more ideas for brainstorming (feel free to ignore them all, they are not ment to be combined with the current version and to be honest I don't find any of them superior to the current one):

- the M could be represented by two gausian-like curves or by a few vertical bars like in the [Mass-Up](http://www.sing-group.org/mass-up/index.php) logo to represent a spectrum.
- may we could replace the gray ring around/behind the R with some ion trajectories to symbolise an ion/orbitrap
- maybe we don't need an R or something in there, e.g. [mMass](http://mmass.org), [OpenChrom](https://openchrom.net/)

**Comment by jorainer** [comment]
> - the M could be represented by two gausian-like curves or by a few vertical bars like in the Mass-Up logo to represent a spectrum.

Nice idea, but I'm afraid it will become *unreadable*. We have already quite some text in the logo, if we start replacing text characters with symbols/illustrations it will be difficult to read.

> - may we could replace the gray ring around/behind the R with some ion trajectories to symbolise an ion/orbitrap

Could you provide a sketch how you would imagine that? One reason I would not like to replace the ring is that this is part of the official R logo and people will recognize it immediately. If we have instead of the ring something else it might be misleading.

> - maybe we don't need an R or something in there, e.g. mMass, OpenChrom

What do you mean? Removing the R logo?

**Comment by jorainer** [comment]
I picked up the idea from @sgibb with the spectrum representation of the ions:

![R4MassSpec-logo_2](https://user-images.githubusercontent.com/5506112/59151756-0dc08300-8a39-11e9-85ff-5873709d0440.png)

Question is if that's now to much? is it still readable? @lgatto ? @sgibb ?

**Comment by sgibb** [comment]
Mh, it looks a little bit busy now. What about a version without the "for MassSpec" text? Or without the x- & y-axis of the spectrum?

**Comment by lgatto** [comment]
I actually like it a lot. But now, I think that the (M)ass (S)pec might not be necessary anymore. Or, as Sebastien suggests, only the R and the ions and spectrum.

**Comment by jorainer** [comment]
it's a dilemma. Without the Mass Spec I think it's too *empty*:

![R4MassSpec-logo_no_text](https://user-images.githubusercontent.com/5506112/59198275-9fdc9e80-8b93-11e9-8bfa-da6bd60bd0ef.png)

- the spectrum is too far from the R logo, but bringing it closer will look weird as the trajectories have a too small angle.

**Comment by jorainer** [comment]
We could play with transparency to put the Mass Spec more in the background:

![R4MassSpec-logo_transparent](https://user-images.githubusercontent.com/5506112/59198423-fe098180-8b93-11e9-8ebb-0a74c102be8b.png)

but then the grey does no longer fit the grey from the R logo.

**Comment by jorainer** [comment]
Alternatively, use transparent coord system (I would not remove them completely, because then it is not clear that it is a spectrum.

![R4MassSpec-logo_transparent_coords](https://user-images.githubusercontent.com/5506112/59198541-445ee080-8b94-11e9-9c5f-345d02609cf8.png)

**Comment by jorainer** [comment]
Alternatively, we could put more emphasis on the spectrum and make it more visible using a drop shadow:

![R4MassSpec-logo copy](https://user-images.githubusercontent.com/5506112/59200239-154a6e00-8b98-11e9-9fee-371992a1b6c4.png)

**Comment by sgibb** [comment]
I really like the one with the drop shadow!

**Comment by jorainer** [comment]
OK, I updated the logo.
