### ISSUE TITLE
RforMassSpectrometry sticker

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/stickers#3]
have been playing a little with stickers and here are the results. I will post each separate so we can vote on them.

**Comment by jorainer** [comment]
**A** the *standard* sticker:

![RforMassSoec-sticker](https://user-images.githubusercontent.com/5506112/59016534-bad0ab00-8841-11e9-8d16-053be511f16b.png)

I personally find that one a little boring, that's why I played with some (more colorful) alternatives.

**Comment by jorainer** [comment]
**B**: the fancy border version. Border is slightly thicker, and re-uses the colors of the ions

![fancy-border](https://user-images.githubusercontent.com/5506112/59016612-eeabd080-8841-11e9-8123-8e69d3d403e0.png)

**Comment by jorainer** [comment]
**C**: the *split beam* version.

![split-beam](https://user-images.githubusercontent.com/5506112/59016657-0be09f00-8842-11e9-9203-f17bfdbe1447.png)

**Comment by jorainer** [comment]
**D**:  the *colored segments* version

![colored-segments](https://user-images.githubusercontent.com/5506112/59016678-1733ca80-8842-11e9-9a29-1e4bef1e5a6e.png)

**Comment by jorainer** [comment]
**E**: the *cube* version:

![cube](https://user-images.githubusercontent.com/5506112/59016734-3af71080-8842-11e9-84db-6351a89aee3d.png)

**Comment by lgatto** [comment]
Could you use camel case for the URL, to make it more readable.

I don't know which one I prefer, probably A (standard), C (split beam) or E (cube), although I am not sure if the cube represents anything or if it's mainly visual.

**Comment by jorainer** [comment]
> Could you use camel case for the URL, to make it more readable.

sure.

My favorites are C and E. I like E mostly because it looks different to the *conventional* stickers, so it would pop out. Point is the cube does not stand for anything. I will have to print all of them in the original size and check how they look then.

**Comment by jorainer** [comment]
I've added the sticker (see https://github.com/rformassspectrometry/stickers/tree/master/sticker). I'm OK with this, let me know if you want any changes @lgatto @sgibb
