### ISSUE TITLE
Produce and order stickers 

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/stickers#4]
Get them!

**Comment by lgatto** [comment]
@jorainer is Stickermule still the recommended provider?

**Comment by jorainer** [comment]
I'd say yes. They have a good quality. Are you ordering or should I?

**Comment by lgatto** [comment]
I'm happy to order and pay. How many would you suggest?

**Comment by jorainer** [comment]
what about 100? it get's cheaper when you order more.

**Comment by lgatto** [comment]
Ok. Do you want me to also order some `mzR`, `xcms` and/or `MSnbase` stickers?

**Comment by jorainer** [comment]
I still do have some `xcms` stickers, so no need for them. For the others - I leave it to you.

**Comment by lgatto** [comment]
Could you remind me of the size of the die cut stickers. Is it 50 mm by 50 mm, or custom?

Any specific instructions?

**Comment by jorainer** [comment]
It's the *default*  50mm x 50mm. No additional instructions.

**Comment by lgatto** [comment]
I've ordered 200 R for Mass Spectrometry and 50 mzR and MSnbase each. I can send you some, of course.

**Comment by jorainer** [comment]
Actually - no need to send any to me, just bring them to CSAMA2019

**Comment by lgatto** [comment]
Will do.

@sgibb - would like me to send you some? Let me know on slack if so.
