### ISSUE TITLE
Sticker for `MsCoreUtils`

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/stickers#5]
Add a sticker for `MsCoreUtils`:

- [x] drawing.
- [x] colors. Ideally re-use the colors used for the RforMassSpec logo to have everything coherent (to a certain extend).

**Comment by jorainer** [comment]
3 different options:

1) plain

![MsCoreUtils_plain](https://user-images.githubusercontent.com/5506112/61376695-f4192380-a8a1-11e9-9c25-d2ac9e710fda.png)

2) single ray

![MsCoreUtils_single](https://user-images.githubusercontent.com/5506112/61376730-ff6c4f00-a8a1-11e9-86ee-2f91ca9ee6aa.png)

3) full

![MsCoreUtils_full](https://user-images.githubusercontent.com/5506112/61376738-07c48a00-a8a2-11e9-859a-9741f4ac29f6.png)

Some comments:
- printout looks OK, only the URL can not be read (that's however the same problem also for Bioconductor stickers).
- the idea with the *ray*: the RforMassSpec sticker has the 3 rays yellow, orange, purple. The idea here was to use one of these colors for the sticker border, and have also just one ray, the same as the border color. That way we could use one of these 3 main colors for the border of all our stickers, and eventually add also the corresponding ray.

Happy for any feedback @lgatto @sgibb

**Comment by jorainer** [comment]
Or use the same layout & colors than the `RforMasSpec` sticker?

![MsCoreUtils](https://user-images.githubusercontent.com/5506112/61377310-3d1da780-a8a3-11e9-89cf-023a50c70c7a.png)

**Comment by lgatto** [comment]
I prefer the 3 rays - I think it would be great if we could have the same background for all the *RforMassSpectrometry* stickers, so that one can instantly recognise the project. 

My preferred sticker is the last one, with the grey border, by a mile.

**Comment by sgibb** [comment]
I also prefer the one with the grey border. I even can read the url there (at least on my high-resolution screen).

**Comment by lgatto** [comment]
And your eagle sight!

**Comment by jorainer** [comment]
@sgibb is still young 😉 

OK, so it will be the last. I will tweak the image and the package font size a little and will then push the changes.

**Comment by lgatto** [comment]
There's also `Spectra`, `Chromatograms`, `MsExperiment` and possible `Features` (I you have time or feel inspired) :-)

**Comment by jorainer** [comment]
I have an idea for `Spectra`, but the others...

**Comment by lgatto** [comment]
One at a time...

**Comment by jorainer** [comment]
I've added the sticker - but before ordeing it in large numbers we should order a small quantity to check that lines are not too thin - and I might even find time to design the Spectra sticker too.
