### ISSUE TITLE
Sticker for Spectra

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/stickers#6]
**Spectra** (shouting out loud) sounds like a super-hero - so I'll try one design based on that.

**Comment by jorainer** [comment]
Suggestion:

<img width="789" alt="Spectra-hero" src="https://user-images.githubusercontent.com/5506112/61438965-e6ff4180-a940-11e9-9efd-3d8d195356ff.png">

So, the *Super*-Spectra - so powerfull 😄 
@sgibb @lgatto suggestions?

**Comment by lgatto** [comment]
I doubt anything can trump this suggestion!

**Comment by jorainer** [comment]
So that's the *final* version. Let me know if I should change something.

![Spectra](https://user-images.githubusercontent.com/5506112/61452743-c349f480-a95c-11e9-9c30-02a75fe61dc7.png)

**Comment by lgatto** [comment]
It's glorious and heroic!

**Comment by jorainer** [comment]
Now the pressure is on us to make the package as efficient and performant as advertised 😉
