### ISSUE TITLE
Sticker for Chromatograms

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/stickers#7]
I was thinking about a sticker for chromatograms - since we're plotting there intensities along retention time I thought we could use a clock and use the clock-pointers as coordinate system.
A draft of that idea:

<img width="688" alt="Chromatograms-clock" src="https://user-images.githubusercontent.com/5506112/61517366-5f303a80-aa07-11e9-8702-f65e5ba617c9.png">

Is that acceptable @lgatto @sgibb ? Do you have other ideas?

**Comment by sgibb** [comment]
Nice, but I am afraid the detailed clock face wouldn't be visible on the sticker.

**Comment by jorainer** [comment]
I can try - no problem to leave out some of the details. But if the general idea is acceptable I will go ahead with coloring etc

**Comment by sgibb** [comment]
I like it.

**Comment by jorainer** [comment]
Added the sticker.
