### ISSUE TITLE
Features sticker

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/stickers#8]
![Features](https://user-images.githubusercontent.com/384198/62232883-9ae3e080-b3c7-11e9-9110-edc7cd20e5f8.png)
An first attempt to design a `Features` sticker - @sgibb @jorainer, any comments or suggestions?

**Comment by lgatto** [comment]
I'll try it out with a different colour gradient - for example from light grey/blue to dark blue.

Will also use thicker solid lines.

**Comment by jorainer** [comment]
Nice! Yes, a different color gradient might be better. Yes and thicker solid (grey?) lines might also look nice. 👍

**Comment by lgatto** [comment]
Second attempt:
![Features](https://user-images.githubusercontent.com/384198/62276361-2a2ed980-b444-11e9-9642-6932a09f0243.png)

**Comment by sgibb** [comment]
The stronger lines are way better but the contrast of the heatmaps is too low.

**Comment by lgatto** [comment]
I'll try with a box around the heatmaps.

**Comment by lgatto** [comment]
How's this?

![Features](https://user-images.githubusercontent.com/384198/62289595-6459a480-b45f-11e9-9c7d-90688f6210bd.png)

**Comment by jorainer** [comment]
Could you try dark grey instead of black?

**Comment by lgatto** [comment]
Here it is.

![Features](https://user-images.githubusercontent.com/384198/62408905-d5b86500-b5cf-11e9-9604-c73686d4e294.png)

- +1 for grey (this one)
- -1 for black (previous one)

Also, I think I will decrease the font used for the package name a bit, once this is settled.

**Comment by lgatto** [comment]
With a smaller font

![Features](https://user-images.githubusercontent.com/384198/62426572-beb86680-b6e6-11e9-89e3-91104f113217.png)
