### ISSUE TITLE
MsExperiment sticker

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/stickers#9]
I thought that a nice theme for the `MsExperiment` package would be a conductor, that conducts all other packages in a coherent way. Here are some doodles my wife made on that theme - we could have one like these with spectra/chromatograms/features in the background. 

![IMG_20190801_132349](https://user-images.githubusercontent.com/384198/62289885-2e68f000-b460-11e9-9ff6-ff090df67941.jpg)

What do you think @sgibb @jorainer ?

**Comment by sgibb** [comment]
Great idea! I like the coloured one most (or the upper left, they are both the same, the colours should be the ones @jorainer used in the RforMassSpectrometry sticker).

**Comment by jorainer** [comment]
Awesome! I like the one in the middle the most. the notes could then even blend into consecutive spectra and chromatograms

**Comment by lgatto** [comment]
I had a go to show the kind of design I was thinking of. The conductor needs to be cut, the MS data is clumsy, there could be some arrows pointing from the XICs to some heatmap cells, ... but it conveys the message. 

![MsExperiment](https://user-images.githubusercontent.com/384198/62426581-da237180-b6e6-11e9-9f30-67f7f24c4af9.png)

**Comment by sgibb** [comment]
To be honest I find the spectra/chromatogram/heatmap overlay too busy. What about converting the right hand side of the five-line staff in your initial doodles into trajectories and a simplified mass spectrum as @jorainer did it on the RforMassSpectrometry logo/sticker?

**Comment by lgatto** [comment]
OK, I'll try that.

**Comment by lgatto** [comment]
Something like that could be sobre and nice.
![](https://i.imgur.com/fG19MGg.jpg)

**Comment by lgatto** [comment]
Or this one

![](https://i.imgur.com/OqcqX3x.jpg)

**Comment by lgatto** [comment]
With the latest scales design

![MsExperiment](https://user-images.githubusercontent.com/384198/62446676-a6d2f800-b763-11e9-9253-dac9ddc0118b.png)

**Comment by sgibb** [comment]
I really like that one. The traces should not interfere with the `MsExperiment` title and maybe some colours would be nice.

**Comment by lgatto** [comment]
Maybe @jorainer, who has an artistic fiber, will have a go when he has a chance. I'll hopefully have some time next week.

**Comment by jorainer** [comment]
I like the idea of the notes-lines that becode chromatograms (or similar). Very nice! I could give it a try - but am relatively budy at present because of internal deadlines (managing budgets, projects, ... )

**Comment by lgatto** [comment]
Feel free if you et a chance. I haven't been able to do anything since when I posted the last comment.

**Comment by jorainer** [comment]
I've the following suggestion:

I wanted the conductor to be a little bit more *active* (and with passion). I would color the chromatograms differently (same color as the mass peaks). Let me please know what you think about the concept @lgatto and @sgibb before I start coloring.

![MsExperiment-drawing](https://user-images.githubusercontent.com/5506112/63423322-566ac400-c40c-11e9-85c5-a70841a7c685.png)

**Comment by jorainer** [comment]
sorry, couldn't stop - what do you think?

![MsExperiment](https://user-images.githubusercontent.com/5506112/63427903-85863300-c416-11e9-99bb-30ba8438290f.png)

**Comment by lgatto** [comment]
Yes, I can feel the passion! Fantastic. I'm going to wait for this one before ordering the big batch.

**Comment by jorainer** [comment]
Wait one more day please - I'll give it another try tomorrow

**Comment by jorainer** [comment]
Updated version. If OK with you I would push it to the repo.

![MsExperiment](https://user-images.githubusercontent.com/5506112/63500678-95f7e580-c4ca-11e9-9b44-6aabfb0d63ce.png)

**Comment by lgatto** [comment]
Nice! What about using a grey for the lighter parts of the conductor's suit?

**Comment by jorainer** [comment]
Like that?

![MsExperiment](https://user-images.githubusercontent.com/5506112/63513291-1415b580-c4e6-11e9-8150-c58796450f08.png)

**Comment by lgatto** [comment]
Yes! Fantastic.

**Comment by jorainer** [comment]
OK. Sticker uploaded.

**Comment by lgatto** [comment]
Thank you Jo, it looks really great. Will order a batch.
